// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// evalConc2_cpp
NumericVector evalConc2_cpp(S4 OCN, IntegerVector ss, NumericVector AS, double tau, NumericVector p, String str, bool normalize);
RcppExport SEXP _eDITH_evalConc2_cpp(SEXP OCNSEXP, SEXP ssSEXP, SEXP ASSEXP, SEXP tauSEXP, SEXP pSEXP, SEXP strSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type OCN(OCNSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type AS(ASSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< String >::type str(strSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(evalConc2_cpp(OCN, ss, AS, tau, p, str, normalize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_eDITH_evalConc2_cpp", (DL_FUNC) &_eDITH_evalConc2_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_eDITH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
