# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evalConc2_cpp <- function(OCN, ss, AS, tau, p, str = "RN", normalize = FALSE) {
    .Call(`_eDITH_evalConc2_cpp`, OCN, ss, AS, tau, p, str, normalize)
}

